version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  neo4j:
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/s3cr3t
    ports:
      - "7474:7474"
      - "7687:7687"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
